## Introduction to DICOM and basic preprocessing

In this notebook, we will explore two common medical imaging file formats: **DICOM (Digital Imaging and Communications in Medicine)** This format is widely used in clinical and research environments respectively.

The main objectives of this module are:
- Understanding DICOM Files
- Basic Image Visualization 
- Basic Preprocessing and Image Quality Assessment

### 1. Introduction to DICOM Files

#### What is a DICOM File?
[DICOM](https://www.dicomstandard.org/) (Digital Imaging and COmmunications in Medicine) is the de-facto standard that establishes rules that allow medical images (X-Ray, MRI, CT) and associated information to be exchanged between imaging equipment from different vendors, computers, and hospitals. It not only stores the image but also includes important metadata such as patient details, modality (e.g., CT, MRI), image orientation, pixel spacing, and much more. The DICOM format provides a suitable means that meets health information exchange (HIE) standards for transmission of health related data among facilities and HL7 standards which is the messaging standard that enables clinical applications to exchange data.

DICOM files typically have a .dcm extension and provides a means of storing data in separate ‘tags’ such as patient information, image/pixel data, the machine used, etc.

For more information, refer to : https://www.dicomstandard.org/about-home

#### Use Cases:
- **DICOM** is heavily used in hospitals and clinics because it integrates with medical imaging equipment.
- **Clinical Metadata**: DICOM files include vital information about the patient and imaging modality, which is essential for diagnosis and treatment.

#### Structure of a DICOM File
A typical DICOM file contains:
- **Header**: Contains metadata such as patient ID, modality, and image acquisition details.
- **Image Data**: The pixel data representing the actual image.

#### Load and read a DICOM image


The following package supports working with DICOM files:

- [pydicom](https://pydicom.github.io/) is a dedicated library for handling DICOM files, allowing access to both pixel data and the associated metadata (e.g., patient details, equipment information, scan parameters). pydicom is ideal when working in medical contexts where you need to inspect, modify, or extract specific information from the DICOM headers in addition to the image data. `pydicom` is best for comprehensive access to both image and metadata, useful when medical details are required for further analysis. It provides pixel data as a NumPy array via the pixel_array attribute, which can be processed and visualized easily. `pydicom` is commonly used with `numpy` and `matplotlib`. `numpy` provides a flexible and efficient structure (the NumPy array) to store and manipulate image data across all three libraries (imageio, pydicom, and scipy.ndimage) and `matplotlib.pyplot` is used to visualize the image data after it's loaded and processed, displaying it in an intuitive and customizable way.


When working with DICOM files, they may sometimes be compressed into a .zip archive. To handle this, we first need to unzip the files before reading them. This can be done easily using Python's `zipfile` module to unzip the DICOM file, or you can unzip the file using the GUI.

To read the image, using the `pydicom` library use the `dcmread()` function, which gives you access to the pixel data via the pixel_array attribute.

In [ ]:
import zipfile
import os
# Path to the zip file and the directory where the contents will be extracted
zip_file_path = '/path/to/your/dicom_files.zip'
extract_dir = '/path/to/extract/'

# Check if the zip file exists
if os.path.exists(zip_file_path):
    # Unzip the file
    with zipfile.ZipFile(zip_file_path, 'r') as zip_ref:
        zip_ref.extractall(extract_dir)
    print(f"Extracted files to {extract_dir}")
    
    # List the contents of the extracted folder
    extracted_files = os.listdir(extract_dir)
    print("Extracted DICOM files:")
    for file in extracted_files:
        print(file)
else:
    print(f"Zip file not found: {zip_file_path}")

# Directory containing your DICOM files
dicom_dir = '/path/to/extracted/DICOM/files'

In [2]:
#Load required libraries
import pydicom
import numpy as np
import matplotlib.pyplot as plt
import scipy.ndimage as ndi

In [ ]:
# Load a DICOM file

# -- Your code here -- #

#### Read Metadata

Metadata refers to supplementary information that describes or provides context for the primary data, such as images or documents. In the context of medical imaging, metadata includes details about how, when, and with what equipment an image was acquired. This might involve information such as the date of the scan, scanner settings, patient demographics (excluding personally identifiable information if anonymized), and details about the imaging modality.
Since this scan was acquired for research purposes, the "patient" information does not contain personally-identifying information like the name or birth. date of the person who was scanned.

In [ ]:
print (dicom_data)

In DICOM files, metadata is organized into various elements. These elements store both the image data and essential metadata. 
The print output shows a list of the data elements (or elements for short) present in the dataset, one element per line. The format of each line is:

- `(0008, 0005)`: The element’s tag, as (group number, element number) in hexadecimal

- `Specific Character Set`: the element’s name, if known

- `CS`: The element’s Value Representation (VR), if known

- `‘ISO_IR_100’`: the element’s stored value

There are three main categories of DICOM elements:

- **Standard Elements**: Defined in the DICOM standard, have even group numbers, and store common metadata.
    
    Example:

        `(0008,0016)` - SOP Class UID
        `(0008,0020)` - Study Date
- **Repeating Group Elements**: Allow multiple occurrences at the same level, with group numbers in a range.

    Example:

        `(60xx,3000)` - Overlay Data (where xx can be 0x6000, 0x6002, 0x6004, etc., up to 0x601E).

- **Private Elements**: Created by manufacturers, have odd group numbers, and can store vendor-specific data. 

    Example:

         `(0043,104E)` - [Duration of X-ray on] (Private Element)




This structure allows DICOM to be highly extensible, accommodating both standardized and vendor-specific data. You can explore these elements using pydicom to retrieve both standard and custom metadata from medical images.

In pydicom, you can access all of these elements and their values directly from the DICOM object.

In [ ]:
# Extract and print metadata

# -- Your code here -- #

The `pydicom` library allows you to access the image's pixel data stored in the DICOM file using the pixel_array attribute. This data represents the raw pixel intensity values of the medical image, which can be visualized using libraries like matplotlib.

In the following code, we use pydicom to read the DICOM file and extract the pixel data. We then use matplotlib to display the image in grayscale, which is common for medical images such as X-rays, CT scans, and MRIs.

In [ ]:
# Extract pixel data
dicom_image = dicom_data.pixel_array

# Print the DICOM image as a NumPy array
print("DICOM Image as a NumPy Array:")
print(dicom_image)

In [ ]:
# Print the dimensions of the DICOM image

# -- Your code here -- #


# You can also print some statistics for better readability
#min_pixel, max_pixel and mean_pixel values

# -- Your code here -- #

In [ ]:
# Visualize the DICOM image
plt.imshow(dicom_image, cmap='gray')
plt.title('DICOM Image')
plt.colorbar()
plt.show()

The metadata and pixel information has been extracted here for a single .dcm file. We can also index the multiple .dcm files we extracted and perform the same functions as:

In [ ]:
# Get all DICOM files in the directory
dicom_files = [os.path.join(dicom_dir, f) for f in os.listdir(dicom_dir) if f.endswith('.dcm')]

# Sort files by instance number or another DICOM attribute if required
dicom_files.sort(key=lambda x: pydicom.dcmread(x).InstanceNumber)

# Initialize a list to store all slices
brain_slices = []

# Read each DICOM file and store the pixel data in the brain_slices list
for dicom_file in dicom_files:
    # -- Your code here -- #


# Convert to a NumPy array for easier manipulation (optional)
# -- Your code here -- #

# Now you can access each slice like brain_slice[0], brain_slice[1], etc.
# Print the shape (dimensions) of the brain_slices array
# Print the pixel array of the first slice (brain_slice[0])
# You can also print some statistics for better readability

# -- Your code here -- #

# Visualize the DICOM image
plt.imshow(brain_slices[0], cmap='gray')
plt.title('DICOM Image')
plt.colorbar()
plt.show()

Unlike the 0-255 pixel intensity range in standard images, MRI scans in DICOM format store pixel values that represent signal intensities. MRI images capture different contrasts based on tissue properties (e.g., T1-weighted, T2-weighted, etc.), and these signal intensities can vary widely depending on the type of sequence and scan parameters. Pixel values can range from 0 to very high values (7000-9000 as above), depending on the scanning modality, resolution, and what part of the body is being imaged.

```
[[ 0  0  0 ...  8  5  2]
 [ 0  0  0 ...  6  0  5]
 [ 0  0  0 ... 17 24  5]
 ...
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]]
```
This array represents the raw pixel intensity values of the DICOM slice, where:

- 0 typically represents the background or areas outside the brain, where no signal is detected.
- Higher values represent areas with higher signal intensity, which may correlate with different tissue types or abnormalities (depending on the MRI modality).

The output pixel statistics for slice [0] represents:

- Min pixel value (0): This is common for regions outside the tissue, like air or background.
- Max pixel value (7017): This could correspond to areas of high signal intensity, such as regions with strong MRI signals like blood vessels or contrast-enhanced regions.
- Mean pixel value (1246.57): This gives you an idea of the overall signal intensity of the slice, indicating the average brightness across the slice.

The reason for such values, in comaprison to the traditional 0-255 range we deal with for standard image formats (JPEG, PNG, etc.) is because these formats use 8-bit per channel color depth. These values represent the intensity of each pixel for grayscale images or the intensity of each color channel (red, green, blue) in color images.

In medical images, particularly in formats like DICOM or NIfTI, pixel values represent more than just simple intensity. They often carry information about the tissue characteristics, physical properties (like density or radiodensity), or signal intensities from imaging machines like CT or MRI. These values are stored in floating-point or higher-bit integers to capture a wider dynamic range of intensities, which is essential for accurate diagnosis. 

MRI scanners store signal intensities using 12-bit or 16-bit depth, which means that pixel values can exceed the 255 range of standard images, allowing for much higher precision in intensity values. In this case, the maximum pixel value of 7017 is quite typical for high-resolution medical images, particularly in MRI.
The full range of pixel values might not always be directly useful for visualization. In clinical practice, radiologists use windowing techniques to adjust the display of these pixel values to fit the display range (e.g., 0-255), highlighting specific tissues of interest. However, for data analysis, usually we work with the raw pixel values (like in an array), which preserve the full dynamic range of the MRI scan. 

The non-normalized image displayed perfectly suggests that the DICOM image already contains pixel values in an appropriate range for visualization. Commonly, DICOM files include fields like `RescaleSlope` and `RescaleIntercept`, which transform raw pixel values into a more meaningful range (e.g., Hounsfield units for CT scans). MRI scans often have pixel intensities that map to tissue types or structures in the body, so forcing them into a 0-255 range can remove useful information.

#### Visualize a slice through different planes

Since the data are a 3D NumPy array, it is very easy to "reslice" the image and visualize the head from one of the other two orientations, axial and coronal. Below we pass `:` to select all sagittal slices, and `128` for the second dimension to get the slice midway through the volume, in the axial plane. Again, we omit the third dimension and so `:` is assumed:

In [ ]:
# Function to load DICOM volume
def load_dicom_volume(dicom_dir):
    slices = []
    for filename in sorted(os.listdir(dicom_dir)):
        # -- Your code here -- #
    
    # Stack slices into a 3D volume
    
# Load the volume
# Ensure the volume has the expected dimensions
# Determine middle slices for each plane


# -- Your code here -- #

# Plotting Saggital Plane (Z-axis slices)
# Plotting Coronal Plane (Y-axis slices)
# Plotting Axial Plane (X-axis slices)

# -- Your code here -- #

#### Plotting an image histogram

As we saw above, the image is stored as a NumPy array, in which each voxel in the image is represented as a number, which is mapped to an intensity value in the colourmap when plotting. Larger values appear as brighter (whiter), and lower values appear as darker.

Histograms of the anatomical images show the number of voxels of a given intensity value. These can be informative because the distribution of intensity values in an anatomical image is not uniform. Instead, as we can see above, there are many very dark voxels (outside of the head, and in some of the fluid-filled spaces inside the head), and then clusters of voxels that are darker grey (the grey matter, largely in the cerebral cortex that forms the outer layer of the brain), lighter grey (the white matter that comprises much of the inside of the brain), and also some very bright areas that are primarily due to areas of fat concentration.

We can use ndimage's `.histogram()` function to plot a histogram of our brain volume. We use this rather than the NumPy `histogram` function, because ndimage's function is designed to work with 3D images. This function requires several arguments, including the minimum and maximum intensity values that define the range of the *x* axis of the histogram, and the number of bins:

In [ ]:
# Plot the histogram

# -- Your code here -- #

In the histogram above, there is a large peak close to zero which represents the fact that a large number of voxels in the image don't contain the head at all, and therefore have values at or close to zero. We can see a peak just above 10 on the *x* axis (note that the numbers on the *x* axis are bin numbers, not intensity values), with a slight decrease and then a second small peak just before 20, followed by a flat area. The peaks just above 10 and just below 20 reflect the concentration of similar intensity values corresponding to grey and white matter respectively. 

### Basic Preprocessing and Image Quality Assessment

There are several image quality measurements that are commonly used in medical image analysis to assess the quality of an image, These include metrics that evaluate noise, contrast, sharpness, and overall fidelity of the image. Some key image quality metrics that can be included are:


1. **Signal-to-Noise Ratio (SNR)**: SNR measures the amount of signal present in an image compared to the noise. Higher SNR values indicate clearer images with less noise. The SNR can be calculated by dividing the mean pixel intensity of the signal by the standard deviation of the background (noise).
2. **Contrast-to-Noise Ratio (CNR)**: CNR is similar to SNR but evaluates the contrast between two regions of interest, making it useful for comparing different tissues (e.g., tumor vs. normal tissue). CNR is the difference in mean intensity between two regions divided by the standard deviation of the background.
3. **Sharpness (Edge Detection)**: Sharpness can be quantified by measuring the gradient magnitude at edges in the image. Sharper edges usually correspond to better image quality. You can use methods like the Sobel or Laplacian filter to assess image sharpness.
4. **Root Mean Square Error (RMSE)**:RMSE compares the difference between the original image and a processed version of the image (e.g., after filtering or compression) to evaluate how much detail has been lost. RMSE is calculated by taking the square root of the mean squared difference between two images.

In [ ]:

from scipy.ndimage import sobel, gaussian_filter
from sklearn.metrics import mean_squared_error


# Load the DICOM file
# Define regions (adjust slices as needed)

# 1. Signal-to-Noise Ratio (SNR)
def calculate_snr(image_data, signal_region, noise_region):
    # -- Your code here -- #

print(f"Signal-to-Noise Ratio (SNR): {snr_value}")

# 2. Contrast-to-Noise Ratio (CNR)
def calculate_cnr(image_data, region1, region2, noise_region):
    # -- Your code here -- #

print(f"Contrast-to-Noise Ratio (CNR): {cnr_value}")

# 3. Sharpness
def calculate_sharpness(image_data):
    # -- Your code here -- #
    
print(f"Sharpness: {sharpness_value}")


# 4. Root Mean Square Error (RMSE)
# Apply Gaussian filter to create a processed version of the image

def calculate_rmse(original_image, processed_image):
    # -- Your code here -- #

print(f"Root Mean Square Error (RMSE): {rmse_value}")

# Display a slice of the processed image
# -- Your code here -- #

### Coding Project - Simple Brain Region Segmentation from DICOM Images

In this project, you will work only with the provided DICOM zip file.
Your goal is to perform a simple segmentation of one region of the brain using basic image-processing tools.

You are free to choose:

* which slice to analyze,
* which plane (axial, sagittal, or coronal),
* which segmentation method to use
  (intensity thresholding, histogram-based selection, filtering + threshold,watershed etc.).

### **Tasks**

1. Load the DICOM images

2. Inspect the metadata of at least one slice
   (e.g., SliceLocation, ImageOrientationPatient, PixelSpacing, SliceThickness).
   Use this information to briefly justify **why you selected a particular slice or plane** for segmentation.

3. Visualize the selected slice, and optionally plot its intensity histogram.

4. Choose a simple segmentation strategy to isolate a meaningful brain region
   (for example something resembling grey matter, white matter, or any visibly distinct structure).

5. Create a binary mask that isolates the region based on your chosen method.

6. Apply the mask to the slice and display the segmented region.

7. (Optional but recommended) – Basic Image Quality Measurement

To connect this project with the image-quality section of the lab, compute one of the following metrics on your chosen slice:

- SNR (Signal-to-Noise Ratio)

- CNR (Contrast-to-Noise Ratio)

- Sharpness (e.g., Sobel gradient magnitude)

- RMSE between the original slice and a filtered version (e.g., Gaussian)

A very short explanation about what your chosen metric tells you about the image is enough.

8. Write a short comment discussing:

   * what the segmentation isolates well,
   * what it fails to isolate,
   * the limitations of simple intensity-based methods.

No advanced algorithms are required.
The goal is to explore how basic DICOM information and pixel intensities can guide the segmentation of a brain region.
